name: DartOAuth
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: wk-j <somnuk.wk@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.2
  oauth2: ^1.3.0

dev_dependencies:
  pedantic: ^1.7.0

